### ISSUE TITLE
Parameters settings

### ISSUE THREAD

**Issue by shhsdxsgf230** [uuup123/FC-HAT#2]
Dear author, I try to run the codes but find it hard for me to set suitable parameters. Could you please show more details or instructions about parameters settings? Thank you!

**Comment by uuup123** [comment]
> Dear author, I try to run the codes but find it hard for me to set suitable parameters. Could you please show more details or instructions about parameters settings? Thank you!


Sorry, parameter setting examples are in the file "/FC-HAT/configs/config.py", more details and instructions about parameter setting can be found in the paper.
