### ISSUE TITLE
Object does not exist on the server

### ISSUE THREAD

**Issue by Gemaxis** [uuup123/FC-HAT#3]
Hi,

This is excellent work, but can't get the code when I use "git lfs fetch".
error: failed to fetch some objects from 'https://github.com/uuup123/FC-HAT.git/info/lfs'

**Comment by uuup123** [comment]
> Hi,
> 
> This is excellent work, but can't get the code when I use "git lfs fetch". error: failed to fetch some objects from 'https://github.com/uuup123/FC-HAT.git/info/lfs'

Please try to use 'git clone https://github.com/uuup123/FC-HAT.git'.

**Comment by Gemaxis** [comment]
Sry, I meant to use 'git lfs fetch' to retrieve the model file.
eg: models/layers.py 
[285b8e9ab9e5561f0d1871cac1f73252c6978bd7e7bcd1f64a2fc8dc88666c05] Object does not exist on the server: [410] **Object does not exist on the server**

**Comment by uuup123** [comment]
> Sry, I meant to use 'git lfs fetch' to retrieve the model file. eg: models/layers.py [285b8e9ab9e5561f0d1871cac1f73252c6978bd7e7bcd1f64a2fc8dc88666c05] Object does not exist on the server: [410] **Object does not exist on the server**

- If you have used "git lfs clone" before, you can try "git lfs fetch" and then "git lfs checkout". 

- If it doesn't or doesn't solve your problem, I recommend re-cloning the repository in Git Bash. 

- And if you still have a problem, try running the clone (again in Git Bash) with a GIT_TRACE=1 in front of it, which should help explain what's going on.

**Comment by Gemaxis** [comment]
> > Sry, I meant to use 'git lfs fetch' to retrieve the model file. eg: models/layers.py [285b8e9ab9e5561f0d1871cac1f73252c6978bd7e7bcd1f64a2fc8dc88666c05] Object does not exist on the server: [410] **Object does not exist on the server**
> 
> * If you have used "git lfs clone" before, you can try "git lfs fetch" and then "git lfs checkout".
> * If it doesn't or doesn't solve your problem, I recommend re-cloning the repository in Git Bash.
> * And if you still have a problem, try running the clone (again in Git Bash) with a GIT_TRACE=1 in front of it, which should help explain what's going on.

I tried it all before pulled the issue, and I did it again but wroth nothing.I still think you can't get what I said, could you please check models/layers.py

**Comment by Gemaxis** [comment]
> > Sry, I meant to use 'git lfs fetch' to retrieve the model file. eg: models/layers.py [285b8e9ab9e5561f0d1871cac1f73252c6978bd7e7bcd1f64a2fc8dc88666c05] Object does not exist on the server: [410] **Object does not exist on the server**
> 
> * If you have used "git lfs clone" before, you can try "git lfs fetch" and then "git lfs checkout".
> * If it doesn't or doesn't solve your problem, I recommend re-cloning the repository in Git Bash.
> * And if you still have a problem, try running the clone (again in Git Bash) with a GIT_TRACE=1 in front of it, which should help explain what's going on.

I have attempted all possible solutions before raising the issue, and I repeated your command to no avail. I maintain my belief that my concern might not be clear to you. Could you please verify the **existence** of your Git LFS file, such as 'models/layers.py'? Or just use the normal file format rather than LFS.

**Comment by uuup123** [comment]
> use the normal file format

the normal file format

**Comment by hetang-wang** [comment]
> 你好
> 
> 这是一项出色的工作，但是当我使用“git lfs fetch”时无法获取代码。错误：无法从“https://github.com/uuup123/FC-HAT.git/info/lfs'



> Hi,
> 
> This is excellent work, but can't get the code when I use "git lfs fetch". error: failed to fetch some objects from 'https://github.com/uuup123/FC-HAT.git/info/lfs'

I meet the same problem.Have you solved it yet? How to solve it？Looking forward to your reply, thank you！！！

**Comment by Gemaxis** [comment]
I've attempted various methods to obtain the file like model.py, but all of them have been unsuccessful,  and the author closed this issue.
Btw, I still can't figure out why the author uses 'lfs' format for such a tiny file.

**Comment by uuup123** [comment]
？？？不用lfs就可以的发自我的iPhone------------------ Original ------------------From: Gemaxis  ***@***.***>Date: Sat,Mar 16,2024 0:10 PMTo: uuup123/FC-HAT ***@***.***>Cc: uuup ***@***.***>, State change ***@***.***>Subject: Re: [uuup123/FC-HAT] Object does not exist on the server (Issue #3)
I've attempted various methods to obtain the file like model.py, but all of them have been unsuccessful,  and the author closed this issue.
Btw, I still can't figure out why the author uses 'lfs' format for such a tiny file.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/uuup123/FC-HAT/issues/3#issuecomment-2001566092",
"url": "https://github.com/uuup123/FC-HAT/issues/3#issuecomment-2001566092",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hetang-wang** [comment]
> ？？？不用lfs就可以的发自我的iPhone------------------ Original ------------------From: Gemaxis ***@***.***>Date: Sat,Mar 16,2024 0:10 PMTo: uuup123/FC-HAT ***@***.***>Cc: uuup ***@***.***>, State change ***@***.***>Subject: Re: [uuup123/FC-HAT] Object does not exist on the server (Issue #3) I've attempted various methods to obtain the file like model.py, but all of them have been unsuccessful, and the author closed this issue. Btw, I still can't figure out why the author uses 'lfs' format for such a tiny file. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#3 (comment)](https://github.com/uuup123/FC-HAT/issues/3#issuecomment-2001566092)", "url": "[#3 (comment)](https://github.com/uuup123/FC-HAT/issues/3#issuecomment-2001566092)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Hi!
      No matter I use git clone command or download zip files,files like moldel.py contains content like this "version https://git-lfs.github.com/spec/v1 oid sha256:e873e41ac4ec96048cb3918c7fc831d61514709623800baee50f9d7d9971d6fb size 1934". I tried to use git lfs clone command to get the normal content of them then  ocuur error like this "Object does not exist on the server".
      I can't get the normal file content. Could you please check the lfs file is right or not.Maybe there was a problem with the push.
      Finally, if it is not the above problem, could you please share a complete code file with me?Looking forward to your reply!
My e-mail  address:wgh15802945745@163.com
